### ISSUE TITLE
Error when running the .yxi 

### ISSUE THREAD

**Issue by pbobys** [bobpeers/Alteryx_SDK_Data_Hash#1]
Hello!  This will come in handy for me if I can get it working.  I tried running the .yxi and I get the following error:  Tool installer error:  There was an error loading the configuration: '.', hexadecimal value 0x00, is an invalid character.  Line 1, position 1.  (see screenshot).   
![Alteryx Hash error screenshot](https://user-images.githubusercontent.com/13425994/104774967-917a3f80-5745-11eb-9a75-571df50a857e.png)

**Comment by bobpeers** [comment]
Hi,
sorry about that, it looks like the package file was corrupted in some way. I've just uploaded a new version that works for me. Can you download and try again.

**Comment by pbobys** [comment]
Yes!  It works perfectly now.  THANK YOU!
Pier
    On Saturday, January 16, 2021, 11:06:19 AM EST, Bob Peers <notifications@github.com> wrote:  
 
 


Hi,
sorry about that, it looks like the package file was corrupted in some way. I've just uploaded a new version that works for me. Can you download and try again.

**Comment by bobpeers** [comment]
Good to hear ☺️
